# Generated by Django 3.0.1 on 2019-12-20 13:07

from django.db import migrations, models
import prepapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=prepapp.models.slide_image_path)),
                ('slide_link', models.CharField(max_length=120)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Slideshow',
            },
        ),
    ]
