# Generated by Django 3.0.1 on 2019-12-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(max_length=500)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
