# Generated by Django 3.0.1 on 2019-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepapp', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
