# Generated by Django 3.0.1 on 2019-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepapp', '0003_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=70)),
                ('year', models.IntegerField()),
                ('Placement', models.CharField(choices=[('FTE', 'FTE'), ('Intern', 'Intern')], max_length=7)),
                ('exprience', models.TextField()),
                ('problems', models.TextField()),
                ('display', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
