# Generated by Django 3.0.1 on 2019-12-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepapp', '0004_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='exprience',
            new_name='experience',
        ),
    ]
