# Generated by Django 3.0.1 on 2019-12-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepapp', '0005_auto_20191228_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='Placement',
            new_name='placement',
        ),
    ]
