# Generated by Django 3.0.1 on 2019-12-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepapp', '0006_auto_20191228_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='college',
            field=models.CharField(default='NIT Durgapur', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exp',
            name='credits',
            field=models.CharField(default='Test User 1', max_length=30),
            preserve_default=False,
        ),
    ]
